package com.eight87.strictlykeptboy.backup

import com.eight87.strictlykeptboy.store.TomlTable
import com.eight87.strictlykeptboy.store.TomlValue
import com.eight87.strictlykeptboy.store.TomlWriter
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.apache.commons.compress.archivers.tar.TarArchiveEntry
import org.apache.commons.compress.archivers.tar.TarArchiveOutputStream
import org.apache.commons.compress.compressors.gzip.GzipCompressorOutputStream
import java.io.File
import java.io.OutputStream
import java.nio.file.Files
import java.time.Instant
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter

/**
 * Round 2.17 Phase F.1 — streams a `<parent>` directory tree out as a
 * gzipped tar archive suitable for the Phase G restore path.
 *
 * Why tar+gzip (vs. zip): Android's `java.util.zip.ZipOutputStream`
 * silently dereferences symlinks. The user's calendar repos ship a
 * `CLAUDE.md → AGENTS.md` symlink (per repo convention in CLAUDE.md
 * §"File conventions"); we MUST round-trip that link, so we use Commons
 * Compress's tar writer with [TarArchiveEntry.LF_SYMLINK].
 *
 * Streaming, not buffering. Parents can be hundreds of MB; we walk the
 * tree and write entries straight through the [GzipCompressorOutputStream]
 * → [TarArchiveOutputStream] sandwich without ever materializing the
 * full content in memory.
 *
 * Skips:
 *  - `.skb-root`              — regenerated by the restore path.
 *  - `**\/.git/objects/pack/.tmp*` — JGit pack-write lockfiles, never
 *    safe to copy.
 */
object BackupArchiver {

    /**
     * Phase F.2 — manifest schema written as the FIRST entry in the
     * tar so a partial / truncated read can still surface metadata.
     *
     * Wire-format `skb_version` is the app's `BuildConfig.VERSION_NAME`;
     * `schema_version = 1` is bumped only on a breaking change to the
     * archive layout (entry names, manifest field names, etc.).
     */
    data class Manifest(
        val skbVersion: String,
        val schemaVersion: Int,
        val createdAt: String,
        val repoCount: Int,
        val parentLabel: String,
        val deviceName: String,
        val bytesWritten: Long = 0L,
    )

    private val ISO_UTC = DateTimeFormatter.ISO_OFFSET_DATE_TIME

    /**
     * Stream `parent` (recursively) into `out` as a gzipped tar. The
     * caller owns `out` (typically a SAF `ContentResolver.openOutputStream`)
     * and is responsible for closing it; this function closes the
     * [TarArchiveOutputStream] sandwich it constructs around `out` but
     * not `out` itself.
     *
     * Returns the manifest that was written as the first entry,
     * populated with `bytesWritten` = the count after the gzip writer
     * has flushed (only meaningful if `out` is a counting stream).
     */
    suspend fun export(
        parent: File,
        out: OutputStream,
        skbVersion: String,
        parentLabel: String,
        deviceName: String,
    ): Manifest = withContext(Dispatchers.IO) {
        require(parent.isDirectory) { "parent must be a directory: $parent" }

        // Walk repos once to compute repo_count for the manifest. A repo
        // is any direct child dir of `parent` other than dotfiles. This
        // matches `ParentReconciler.reconcile`'s discovery contract.
        val repoCount = parent.listFiles()
            ?.count { it.isDirectory && !it.name.startsWith(".") }
            ?: 0

        val manifest = Manifest(
            skbVersion = skbVersion,
            schemaVersion = 1,
            createdAt = Instant.now().atOffset(ZoneOffset.UTC).format(ISO_UTC),
            repoCount = repoCount,
            parentLabel = parentLabel,
            deviceName = deviceName,
        )

        val counting = CountingOutputStream(out)
        GzipCompressorOutputStream(counting).use { gz ->
            TarArchiveOutputStream(gz).use { tar ->
                tar.setLongFileMode(TarArchiveOutputStream.LONGFILE_POSIX)
                tar.setBigNumberMode(TarArchiveOutputStream.BIGNUMBER_POSIX)

                // F.2 — manifest must be the first entry.
                val manifestBytes = encodeManifest(manifest).toByteArray(Charsets.UTF_8)
                val manifestEntry = TarArchiveEntry("manifest.toml")
                manifestEntry.size = manifestBytes.size.toLong()
                manifestEntry.modTime = java.util.Date()
                tar.putArchiveEntry(manifestEntry)
                tar.write(manifestBytes)
                tar.closeArchiveEntry()

                walkAndWrite(parent, parent, tar)
            }
        }
        manifest.copy(bytesWritten = counting.count)
    }

    /**
     * Serialize a [Manifest] into the TOML wire format. Hand-rolled via
     * [TomlWriter] per the repo's "no reflection-based JSON" rule.
     */
    internal fun encodeManifest(m: Manifest): String {
        val t = TomlTable()
        t.put("skb_version", TomlValue.Str(m.skbVersion))
        t.put("schema_version", TomlValue.I64(m.schemaVersion.toLong()))
        t.put("created_at", TomlValue.OffsetDateTime(m.createdAt))
        t.put("repo_count", TomlValue.I64(m.repoCount.toLong()))
        t.put("parent_label", TomlValue.Str(m.parentLabel))
        t.put("device_name", TomlValue.Str(m.deviceName))
        return TomlWriter.emit(t)
    }

    private fun walkAndWrite(root: File, dir: File, tar: TarArchiveOutputStream) {
        val children = dir.listFiles() ?: return
        // Deterministic order so the archive is reproducible-ish (mtimes
        // still vary). Helps the round-trip test compare entries.
        children.sortBy { it.name }
        for (child in children) {
            val rel = root.toPath().relativize(child.toPath()).toString()
                .replace(File.separatorChar, '/')

            // Skips per F.1.
            if (rel == ".skb-root") continue
            if (isPackTmp(rel)) continue

            // CRITICAL: check symlink before isDirectory — a symlink to
            // a dir reports isDirectory() = true on the dereferenced
            // target, which would recurse into it.
            val path = child.toPath()
            val isSymlink = Files.isSymbolicLink(path)

            when {
                isSymlink -> {
                    val target = Files.readSymbolicLink(path).toString()
                    val entry = TarArchiveEntry(rel, TarArchiveEntry.LF_SYMLINK)
                    entry.linkName = target
                    entry.modTime = java.util.Date(child.lastModified())
                    tar.putArchiveEntry(entry)
                    tar.closeArchiveEntry()
                }
                child.isDirectory -> {
                    // Emit an explicit dir entry (tar tools tolerate
                    // implicit dirs, but emitting them keeps perms +
                    // empty-dir preservation honest).
                    val entry = TarArchiveEntry(child, "$rel/")
                    tar.putArchiveEntry(entry)
                    tar.closeArchiveEntry()
                    walkAndWrite(root, child, tar)
                }
                child.isFile -> {
                    val entry = TarArchiveEntry(child, rel)
                    tar.putArchiveEntry(entry)
                    child.inputStream().use { it.copyTo(tar) }
                    tar.closeArchiveEntry()
                }
                // Other inodes (sockets, fifos, char/block devices)
                // are silently skipped — they can't exist inside an
                // Android app's data dir or a SAF tree anyway.
            }
        }
    }

    private fun isPackTmp(rel: String): Boolean {
        // Match `<repo>/.git/objects/pack/.tmp*` and bare-repo equivalents.
        val parts = rel.split('/')
        val packIdx = parts.indexOf("pack")
        if (packIdx <= 1) return false
        return parts[packIdx - 1] == "objects" &&
            parts[packIdx - 2] == ".git" &&
            packIdx + 1 < parts.size &&
            parts[packIdx + 1].startsWith(".tmp")
    }

    /**
     * Wraps an [OutputStream] to count bytes written. Used to surface
     * the on-disk archive size for the post-export Toast.
     */
    private class CountingOutputStream(private val inner: OutputStream) : OutputStream() {
        var count: Long = 0L
            private set

        override fun write(b: Int) {
            inner.write(b)
            count += 1
        }

        override fun write(b: ByteArray, off: Int, len: Int) {
            inner.write(b, off, len)
            count += len
        }

        override fun flush() { inner.flush() }
        override fun close() { inner.close() }
    }
}
