package com.eight87.strictlykeptboy.ui.schedule

import com.eight87.strictlykeptboy.git.GitRepoRegistry
import com.eight87.strictlykeptboy.store.EntityWriter
import com.eight87.strictlykeptboy.store.Event
import com.eight87.strictlykeptboy.store.Exception
import com.eight87.strictlykeptboy.store.RecurrenceRule
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.time.LocalDate
import java.time.OffsetDateTime
import java.time.format.DateTimeFormatter

/**
 * Round 2.22 / Phase B UI follow-up — controller side of drag-to-reschedule.
 *
 * Thin orchestrator: takes a [DragReschedule] math result + the repo
 * root, persists it via [EntityWriter], commits via [GitRepoRegistry].
 * No Compose dependency; suspend functions only so that
 * `Robolectric`-free JVM tests can drive it with a tmp directory.
 *
 * SOLID-S: write-orchestration only. Math lives in [DragReschedule];
 * gesture lives in [ScheduleDayView] / [ScheduleWeekView] /
 * [ScheduleThreeDayView]; AlertDialog mount lives in
 * [DragRescheduleRecurrencePrompt].
 *
 * D-2.22.b — auto-commit message format `move event "<title>" from
 * <old-iso> to <new-iso>`, generated by [DragReschedule.commitMessageFor].
 */
object DragRescheduleController {

    /** Choice surfaced by [DragRescheduleRecurrencePrompt]. */
    enum class RecurringChoice { THIS_ONE, THIS_AND_FUTURE, WHOLE_SERIES }

    /**
     * Single-instance event drop. Rewrites the event file in place
     * (duration preserved) + commits with the canonical message.
     *
     * Returns the new [Event] on success, `null` if the move was a
     * no-op (new start == old start).
     */
    suspend fun handleSingleDrop(
        rootDir: File,
        repoId: String,
        event: Event,
        newStart: OffsetDateTime,
        nowIso: String,
    ): Event? = withContext(Dispatchers.IO) {
        val oldStart = event.start
        val moved = DragReschedule.moveSingleEvent(event, newStart, nowIso)
        if (moved.start == oldStart) return@withContext null
        EntityWriter.write(rootDir, moved)
        val msg = DragReschedule.commitMessageFor(
            title = moved.title,
            oldStart = oldStart,
            newStart = moved.start,
        )
        GitRepoRegistry.get(repoId)?.commitAll(msg)
        moved
    }

    /**
     * Recurring-instance drop with the user's branch choice. Returns
     * the canonical commit subject that was used, for telemetry / UI
     * snackbar copy.
     */
    suspend fun handleRecurringDrop(
        rootDir: File,
        repoId: String,
        rule: RecurrenceRule,
        originalDate: LocalDate,
        newStart: OffsetDateTime,
        choice: RecurringChoice,
        author: String?,
        nowIso: String,
    ): String = withContext(Dispatchers.IO) {
        val originalIso = "${originalDate}T${rule.dtstart.substringAfter('T', "00:00:00")}"
        val newIso = newStart.toLocalDateTime().format(LOCAL_DT)
        val msg = when (choice) {
            RecurringChoice.THIS_ONE -> {
                val exception = DragReschedule.moveRecurringInstance(
                    rule = rule,
                    originalDate = originalDate,
                    newStart = newStart,
                    author = author,
                    nowIso = nowIso,
                )
                EntityWriter.write(rootDir, exception)
                DragReschedule.commitMessageFor(rule.title, originalIso, newIso)
            }
            RecurringChoice.THIS_AND_FUTURE -> {
                val (capped, fresh) = DragReschedule.splitRecurringRule(
                    rule = rule,
                    newStart = newStart,
                    author = author,
                    nowIso = nowIso,
                )
                EntityWriter.write(rootDir, capped)
                EntityWriter.write(rootDir, fresh)
                DragReschedule.commitMessageFor(rule.title, originalIso, newIso)
            }
            RecurringChoice.WHOLE_SERIES -> {
                val rewritten = DragReschedule.rewriteRuleDtstart(rule, newStart, nowIso)
                EntityWriter.write(rootDir, rewritten)
                DragReschedule.commitMessageFor(rule.title, rule.dtstart, rewritten.dtstart)
            }
        }
        GitRepoRegistry.get(repoId)?.commitAll(msg)
        msg
    }

    private val LOCAL_DT: DateTimeFormatter =
        DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss")
}
